steps:
- bash: |
    terraform apply -auto-approve $(terraformPlanFile)
  displayName: Terraform Apply
  env:
    ARM_SUBSCRIPTION_ID:        $(kv-subscription-id)
    ARM_CLIENT_ID:              $(kv-spn-id)
    ARM_CLIENT_SECRET:          $(kv-spn-psw)
    ARM_TENANT_ID:              $(kv-tenant-id)
